# Crystal Drops — one-shot deploy script
# Run from this folder with:    .\deploy.ps1

Write-Host "`n  Crystal Drops · Firebase deploy" -ForegroundColor Cyan
Write-Host "  -------------------------------" -ForegroundColor Cyan

# Make sure we're in the right folder
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $here

# 1. Make sure CLI is installed
if (-not (Get-Command firebase -ErrorAction SilentlyContinue)) {
  Write-Host "`nFirebase CLI not found — installing now..." -ForegroundColor Yellow
  npm install -g firebase-tools
}

# 2. Login if needed
$who = firebase login:list 2>&1 | Out-String
if ($who -match "No authorized accounts") {
  Write-Host "`nOpening browser for Firebase login..." -ForegroundColor Yellow
  Write-Host "(Sign in with the Google account that owns your Firebase projects.)`n"
  firebase login --no-localhost
} else {
  Write-Host "`nAlready signed in." -ForegroundColor Green
}

# 3. Set the active project
Write-Host "`nSetting active project..." -ForegroundColor Yellow
firebase use expense-tracker-39c1e

# 4. Register the web app (idempotent — skips if already exists with this nickname)
Write-Host "`nRegistering web app..." -ForegroundColor Yellow
$apps = firebase apps:list web --project expense-tracker-39c1e 2>&1 | Out-String
if ($apps -notmatch "Crystal Drops") {
  firebase apps:create web "Crystal Drops" --project expense-tracker-39c1e
} else {
  Write-Host "  Web app 'Crystal Drops' already exists." -ForegroundColor Green
}

# 5. Pull SDK config and write to firebase-config.js automatically
Write-Host "`nFetching SDK config..." -ForegroundColor Yellow
$sdk = firebase apps:sdkconfig web --project expense-tracker-39c1e 2>&1 | Out-String

# Extract the JSON object from the SDK output
if ($sdk -match '(?s)\{[^{}]*"projectId"[^{}]*\}') {
  $cfg = $matches[0]
  $cfgClean = ($cfg -replace '(?m)^\s*//.*$','') -replace '\s+', ' '
  $js = @"
// Crystal Drops — Firebase config (auto-generated by deploy.ps1)
window.firebaseConfig = $cfg;
"@
  $js | Out-File -FilePath "firebase-config.js" -Encoding utf8
  Write-Host "  Wrote firebase-config.js with live values." -ForegroundColor Green
} else {
  Write-Host "  Could not parse SDK config — you may need to fill firebase-config.js manually." -ForegroundColor Red
  Write-Host $sdk
}

# 6. Deploy
Write-Host "`nDeploying to Firebase Hosting + Firestore..." -ForegroundColor Yellow
firebase deploy

Write-Host "`n  Done. Open the Hosting URL above on your phone." -ForegroundColor Green
